SET NAMES UTF8;
DROP DATABASE IF EXISTS msg;
CREATE DATABASE msg CHARSET=UTF8;
USE msg;
CREATE TABLE t_msg(
	mid		INT PRIMARY KEY AUTO_INCREMENT,
	uname		VARCHAR(16),
	email		VARCHAR(32),
	content	VARCHAR(160),
	launch_time		BIGINT
);