var adv={//面向对象创建
	DISTANCE:0,DURATION:2000,//总距离(div的高)和总时间
	STEPS:400,//总步数，建议DURATION/STEPS>=5ms
	interval:0,step:0,//时间间隔和步长
	moved:0,//已经移动的步数
	div:null,//保存主角div
	timer:null,//保存定时器序号
	WAIT:5000,//下移后等待上移的时间
	init(){//初始化动画的数据:
		//查找主角div
		this.div=document.getElementById("msg");
		//获得总距离(div计算后的高转为浮点数)
		this.DISTANCE=parseFloat(//->为了去单位
			getComputedStyle(this.div).height//getComputedStyle()--->计算后的样式(this.div.style.bottom-->内联样式才可以这样写)
		);
		//计算interval和step
		this.interval=this.DURATION/this.STEPS;
		this.step=this.DISTANCE/this.STEPS;
		this.move(1);//启动上移
		//找到div下的a，绑定单击事件，启动下移
		this.div.children[0].onclick=function(){
			//this->a->adv
			if(this.timer==null)//如果没有动画在运行，才
				this.move(-1);//启动下移
		}.bind(this);
	},
	move(dir){//启动移动
  //启动周期性定时器每隔interval调用一次moveUpStep
		this.timer=setInterval(
			this.moveStep.bind(this,dir),this.interval)
	},
	moveStep(dir){//移动一步
		var bottom=parseFloat(//获得div的bottom
			getComputedStyle(this.div).bottom
		);
		bottom+=dir*this.step;//将bottom+step
		//将bottom设置回div
		this.div.style.bottom=bottom+"px";
		this.moved++;//将moved+1
		if(this.moved==this.STEPS){//如果moved等于STEPS
			//停止定时器,清空timer,moved归0
			clearInterval(this.timer);
			this.timer=null; this.moved=0;
			if(dir==-1){//如果是下移
				setTimeout(//就等待WAIT毫秒再调用move(1)
					this.move.bind(this,1),this.WAIT)
			}
		}//练习10分钟!
	}
}
adv.init(); console.dir(adv);